### ISSUE TITLE
Specific remove rules don't work with Label plugin?

### ISSUE THREAD

**Issue by Brandoskey** [laur89/deluge-autoremoveplus#7]
Is the standard Label plugin not supported? I can't get it to recognize any rules made with labels

As an asside, the specific remove rules are a bit hard to wrap my head around, can we get a basic primer on how the feature is put to use? When do you need to use operators? what are they comparing to?

**Comment by laur89** [comment]
> Is the standard Label plugin not supported?

Yes - `labelplus` in autoremoveplus.conf needs to be set to `false` -- then the vanilla labels are used as opposed to labelplus ones.

> As an asside, the specific remove rules are a bit hard to wrap my head around, can we get a basic primer on how the feature is put to use? When do you need to use operators? what are they comparing to?

Excellent point. Had to originally go through the code to understand how anything works. The UI is especially ambiguous and deceptive. Once I get over my lazies i'll improve the readme. And hopefully the plugin itself.
In the meantime you might find help in [this](https://forum.deluge-torrent.org/viewtopic.php?p=235670#p235670) forum thread.

**Comment by Brandoskey** [comment]
That thread actually did help, I think the reason I couldn't get it to work is none of the checks seem to work on non-seeding torrents.

Basically, what I want is for torrents that never complete to be removed after a given amount of time.

Some trackers like to lie about the number of seeders, so radarr and sonarr will wait until manual intervention to mark unseeded torrents as failed.

Am I right in assuming this functionality isn'tr available in the plugin?

**Comment by laur89** [comment]
> Am I right in assuming this functionality isn'tr available in the plugin?

Correct. Feel free to open a ticket for it though, it does sound like a reasonable requirement.
